// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'types.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

BarcodeModuleSettings _$BarcodeModuleSettingsFromJson(
  Map<String, dynamic> json,
) => BarcodeModuleSettings(
  presenceMandatory: json['presenceMandatory'] as bool? ?? false,
  barcodeImageReturnEnabled:
      json['barcodeImageReturnEnabled'] as bool? ?? false,
  pdf417ScanningEnabled: json['pdf417ScanningEnabled'] as bool? ?? true,
  qrScanningEnabled: json['qrScanningEnabled'] as bool? ?? true,
  upceScanningEnabled: json['upceScanningEnabled'] as bool? ?? false,
  upcaScanningEnabled: json['upcaScanningEnabled'] as bool? ?? false,
  code128ScanningEnabled: json['code128ScanningEnabled'] as bool? ?? false,
  code39ScanningEnabled: json['code39ScanningEnabled'] as bool? ?? false,
  ean8ScanningEnabled: json['ean8ScanningEnabled'] as bool? ?? false,
  ean13ScanningEnabled: json['ean13ScanningEnabled'] as bool? ?? false,
  itfScanningEnabled: json['itfScanningEnabled'] as bool? ?? false,
  dataMatrixScanningEnabled:
      json['dataMatrixScanningEnabled'] as bool? ?? false,
  aztecScanningEnabled: json['aztecScanningEnabled'] as bool? ?? false,
);

Map<String, dynamic> _$BarcodeModuleSettingsToJson(
  BarcodeModuleSettings instance,
) => <String, dynamic>{
  'presenceMandatory': instance.presenceMandatory,
  'barcodeImageReturnEnabled': instance.barcodeImageReturnEnabled,
  'pdf417ScanningEnabled': instance.pdf417ScanningEnabled,
  'qrScanningEnabled': instance.qrScanningEnabled,
  'upceScanningEnabled': instance.upceScanningEnabled,
  'upcaScanningEnabled': instance.upcaScanningEnabled,
  'code128ScanningEnabled': instance.code128ScanningEnabled,
  'code39ScanningEnabled': instance.code39ScanningEnabled,
  'ean8ScanningEnabled': instance.ean8ScanningEnabled,
  'ean13ScanningEnabled': instance.ean13ScanningEnabled,
  'itfScanningEnabled': instance.itfScanningEnabled,
  'dataMatrixScanningEnabled': instance.dataMatrixScanningEnabled,
  'aztecScanningEnabled': instance.aztecScanningEnabled,
};

DocumentCaptureModuleSettings _$DocumentCaptureModuleSettingsFromJson(
  Map<String, dynamic> json,
) => DocumentCaptureModuleSettings(
  cropType:
      $enumDecodeNullable(_$InputImageCropTypeEnumMap, json['cropType']) ??
      InputImageCropType.notCropped,
  unsupportedDocumentsAllowed:
      json['unsupportedDocumentsAllowed'] as bool? ?? false,
  secondSideWithNoExtractableDataSkipped:
      json['secondSideWithNoExtractableDataSkipped'] as bool? ?? true,
  passportDataPageScanOnly: json['passportDataPageScanOnly'] as bool? ?? true,
  faceImageExtractionEnabled:
      json['faceImageExtractionEnabled'] as bool? ?? false,
  faceImagePresenceMandatory:
      json['faceImagePresenceMandatory'] as bool? ?? false,
  inputImageReturnEnabled: json['inputImageReturnEnabled'] as bool? ?? false,
  documentImageReturnEnabled:
      json['documentImageReturnEnabled'] as bool? ?? false,
  inputImageMargin: (json['inputImageMargin'] as num?)?.toDouble() ?? 0.02,
  dotsPerInch: (json['dotsPerInch'] as num?)?.toInt() ?? 250,
  extensionFactor: (json['extensionFactor'] as num?)?.toDouble() ?? 0.0,
  blurSensitivityLevel:
      $enumDecodeNullable(
        _$SensitivityLevelEnumMap,
        json['blurSensitivityLevel'],
      ) ??
      SensitivityLevel.mid,
  imageWithBlurRejected: json['imageWithBlurRejected'] as bool? ?? true,
  glareSensitivityLevel:
      $enumDecodeNullable(
        _$SensitivityLevelEnumMap,
        json['glareSensitivityLevel'],
      ) ??
      SensitivityLevel.mid,
  imageWithGlareRejected: json['imageWithGlareRejected'] as bool? ?? true,
  tiltSensitivityLevel:
      $enumDecodeNullable(
        _$SensitivityLevelEnumMap,
        json['tiltSensitivityLevel'],
      ) ??
      SensitivityLevel.mid,
  imageWithPoorLightingRejected:
      json['imageWithPoorLightingRejected'] as bool? ?? true,
  imageWithHandOcclusionRejected:
      json['imageWithHandOcclusionRejected'] as bool? ?? true,
  inputImageSelectionStrategy:
      $enumDecodeNullable(
        _$InputImageSelectionStrategyEnumMap,
        json['inputImageSelectionStrategy'],
      ) ??
      InputImageSelectionStrategy.balanced,
);

Map<String, dynamic> _$DocumentCaptureModuleSettingsToJson(
  DocumentCaptureModuleSettings instance,
) => <String, dynamic>{
  'cropType': _$InputImageCropTypeEnumMap[instance.cropType]!,
  'unsupportedDocumentsAllowed': instance.unsupportedDocumentsAllowed,
  'secondSideWithNoExtractableDataSkipped':
      instance.secondSideWithNoExtractableDataSkipped,
  'passportDataPageScanOnly': instance.passportDataPageScanOnly,
  'faceImageExtractionEnabled': instance.faceImageExtractionEnabled,
  'faceImagePresenceMandatory': instance.faceImagePresenceMandatory,
  'inputImageReturnEnabled': instance.inputImageReturnEnabled,
  'documentImageReturnEnabled': instance.documentImageReturnEnabled,
  'inputImageMargin': instance.inputImageMargin,
  'dotsPerInch': instance.dotsPerInch,
  'extensionFactor': instance.extensionFactor,
  'blurSensitivityLevel':
      _$SensitivityLevelEnumMap[instance.blurSensitivityLevel]!,
  'imageWithBlurRejected': instance.imageWithBlurRejected,
  'glareSensitivityLevel':
      _$SensitivityLevelEnumMap[instance.glareSensitivityLevel]!,
  'imageWithGlareRejected': instance.imageWithGlareRejected,
  'tiltSensitivityLevel':
      _$SensitivityLevelEnumMap[instance.tiltSensitivityLevel]!,
  'imageWithPoorLightingRejected': instance.imageWithPoorLightingRejected,
  'imageWithHandOcclusionRejected': instance.imageWithHandOcclusionRejected,
  'inputImageSelectionStrategy':
      _$InputImageSelectionStrategyEnumMap[instance
          .inputImageSelectionStrategy]!,
};

const _$InputImageCropTypeEnumMap = {
  InputImageCropType.notCropped: 'not-cropped',
  InputImageCropType.unknown: 'unknown',
  InputImageCropType.cropped: 'cropped',
};

const _$SensitivityLevelEnumMap = {
  SensitivityLevel.off: 'off',
  SensitivityLevel.low: 'low',
  SensitivityLevel.mid: 'mid',
  SensitivityLevel.high: 'high',
};

const _$InputImageSelectionStrategyEnumMap = {
  InputImageSelectionStrategy.singleImage: 'single-image',
  InputImageSelectionStrategy.optimizeForSpeed: 'optimize-for-speed',
  InputImageSelectionStrategy.balanced: 'balanced',
  InputImageSelectionStrategy.optimizeForQuality: 'optimize-for-quality',
};

MrzModuleSettings _$MrzModuleSettingsFromJson(Map<String, dynamic> json) =>
    MrzModuleSettings(
      presenceMandatory: json['presenceMandatory'] as bool? ?? false,
    );

Map<String, dynamic> _$MrzModuleSettingsToJson(MrzModuleSettings instance) =>
    <String, dynamic>{'presenceMandatory': instance.presenceMandatory};

VizModuleSettings _$VizModuleSettingsFromJson(Map<String, dynamic> json) =>
    VizModuleSettings(
      presenceMandatory: json['presenceMandatory'] as bool? ?? false,
      signatureImageExtractionEnabled:
          json['signatureImageExtractionEnabled'] as bool? ?? false,
      characterValidationEnabled:
          json['characterValidationEnabled'] as bool? ?? true,
      resultAggregationEnabled:
          json['resultAggregationEnabled'] as bool? ?? true,
    );

Map<String, dynamic> _$VizModuleSettingsToJson(
  VizModuleSettings instance,
) => <String, dynamic>{
  'presenceMandatory': instance.presenceMandatory,
  'signatureImageExtractionEnabled': instance.signatureImageExtractionEnabled,
  'characterValidationEnabled': instance.characterValidationEnabled,
  'resultAggregationEnabled': instance.resultAggregationEnabled,
};

ClassFilter _$ClassFilterFromJson(Map<String, dynamic> json) => ClassFilter()
  ..includeDocuments = (json['includeDocuments'] as List<dynamic>?)
      ?.map((e) => DocumentFilter.fromJson(e as Map<String, dynamic>))
      .toList()
  ..excludeDocuments = (json['excludeDocuments'] as List<dynamic>?)
      ?.map((e) => DocumentFilter.fromJson(e as Map<String, dynamic>))
      .toList();

Map<String, dynamic> _$ClassFilterToJson(ClassFilter instance) =>
    <String, dynamic>{
      'includeDocuments': instance.includeDocuments,
      'excludeDocuments': instance.excludeDocuments,
    };

RedactionSettings _$RedactionSettingsFromJson(Map<String, dynamic> json) =>
    RedactionSettings(
      fields: (json['fields'] as List<dynamic>)
          .map((e) => $enumDecode(_$FieldTypeEnumMap, e))
          .toList(),
      mode:
          $enumDecodeNullable(_$RedactionModeEnumMap, json['mode']) ??
          RedactionMode.fullResult,
      documentNumberRedactionSettings:
          json['documentNumberRedactionSettings'] == null
          ? null
          : DocumentNumberRedactionSettings.fromJson(
              json['documentNumberRedactionSettings'] as Map<String, dynamic>,
            ),
      redactBarcodeResult: json['redactBarcodeResult'] as bool? ?? false,
      redactMrzResult: json['redactMrzResult'] as bool? ?? false,
      documentFilter: (json['documentFilter'] as List<dynamic>?)
          ?.map((e) => DocumentFilter.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$RedactionSettingsToJson(
  RedactionSettings instance,
) => <String, dynamic>{
  'mode': _$RedactionModeEnumMap[instance.mode]!,
  'fields': instance.fields.map((e) => _$FieldTypeEnumMap[e]!).toList(),
  'documentNumberRedactionSettings': instance.documentNumberRedactionSettings,
  'redactMrzResult': instance.redactMrzResult,
  'redactBarcodeResult': instance.redactBarcodeResult,
  'documentFilter': instance.documentFilter,
};

const _$FieldTypeEnumMap = {
  FieldType.additionalAddressInformation: 'additionalAddressInformation',
  FieldType.additionalNameInformation: 'additionalNameInformation',
  FieldType.additionalOptionalAddressInformation:
      'additionalOptionalAddressInformation',
  FieldType.additionalPersonalIdNumber: 'additionalPersonalIdNumber',
  FieldType.address: 'address',
  FieldType.classEffectiveDate: 'classEffectiveDate',
  FieldType.classExpiryDate: 'classExpiryDate',
  FieldType.conditions: 'conditions',
  FieldType.dateOfBirth: 'dateOfBirth',
  FieldType.dateOfExpiry: 'dateOfExpiry',
  FieldType.dateOfIssue: 'dateOfIssue',
  FieldType.documentAdditionalNumber: 'documentAdditionalNumber',
  FieldType.documentOptionalAdditionalNumber:
      'documentOptionalAdditionalNumber',
  FieldType.documentNumber: 'documentNumber',
  FieldType.employer: 'employer',
  FieldType.endorsements: 'endorsements',
  FieldType.fathersName: 'fathersName',
  FieldType.firstName: 'firstName',
  FieldType.fullName: 'fullName',
  FieldType.issuingAuthority: 'issuingAuthority',
  FieldType.lastName: 'lastName',
  FieldType.licenceType: 'licenceType',
  FieldType.localizedName: 'localizedName',
  FieldType.maritalStatus: 'maritalStatus',
  FieldType.mothersName: 'mothersName',
  FieldType.mrz: 'mrz',
  FieldType.nationality: 'nationality',
  FieldType.personalIdNumber: 'personalIdNumber',
  FieldType.placeOfBirth: 'placeOfBirth',
  FieldType.profession: 'profession',
  FieldType.race: 'race',
  FieldType.religion: 'religion',
  FieldType.residentialStatus: 'residentialStatus',
  FieldType.restrictions: 'restrictions',
  FieldType.sex: 'sex',
  FieldType.vehicleClass: 'vehicleClass',
  FieldType.bloodType: 'bloodType',
  FieldType.sponsor: 'sponsor',
  FieldType.visaType: 'visaType',
  FieldType.documentSubtype: 'documentSubtype',
  FieldType.remarks: 'remarks',
  FieldType.residencePermitType: 'residencePermitType',
  FieldType.manufacturingYear: 'manufacturingYear',
  FieldType.vehicleType: 'vehicleType',
  FieldType.dependentDateOfBirth: 'dependentDateOfBirth',
  FieldType.dependentSex: 'dependentSex',
  FieldType.dependentDocumentNumber: 'dependentDocumentNumber',
  FieldType.dependentFullName: 'dependentFullName',
  FieldType.eligibilityCategory: 'eligibilityCategory',
  FieldType.specificDocumentValidity: 'specificDocumentValidity',
  FieldType.vehicleOwner: 'vehicleOwner',
  FieldType.nationalInsuranceNumber: 'nationalInsuranceNumber',
  FieldType.countryCode: 'countryCode',
  FieldType.certificateNumber: 'certificateNumber',
  FieldType.municipalityOfRegistration: 'municipalityOfRegistration',
  FieldType.localityCode: 'localityCode',
  FieldType.maidenName: 'maidenName',
  FieldType.stateCode: 'stateCode',
  FieldType.dateOfEntry: 'dateOfEntry',
  FieldType.municipalityCode: 'municipalityCode',
  FieldType.pollingStationCode: 'pollingStationCode',
  FieldType.sectionCode: 'sectionCode',
  FieldType.registrationCenterCode: 'registrationCenterCode',
  FieldType.stateName: 'stateName',
  FieldType.effectiveDate: 'effectiveDate',
  FieldType.parentsLastName: 'parentsLastName',
  FieldType.parentsFirstName: 'parentsFirstName',
  FieldType.workRestriction: 'workRestriction',
  FieldType.socialSecurityStatus: 'socialSecurityStatus',
  FieldType.legalStatus: 'legalStatus',
  FieldType.husbandName: 'husbandName',
  FieldType.cardAccessNumber: 'cardAccessNumber',
  FieldType.parentFullName: 'parentFullName',
  FieldType.ethnicity: 'ethnicity',
};

const _$RedactionModeEnumMap = {
  RedactionMode.none: 'none',
  RedactionMode.imageOnly: 'imageOnly',
  RedactionMode.resultFieldsOnly: 'resultFieldsOnly',
  RedactionMode.fullResult: 'fullResult',
};

RedactionSettingsResolver _$RedactionSettingsResolverFromJson(
  Map<String, dynamic> json,
) => RedactionSettingsResolver(
  (json['documentRedactionList'] as List<dynamic>)
      .map((e) => RedactionSettings.fromJson(e as Map<String, dynamic>))
      .toList(),
);

Map<String, dynamic> _$RedactionSettingsResolverToJson(
  RedactionSettingsResolver instance,
) => <String, dynamic>{
  'documentRedactionList': instance.documentRedactionList
      .map((e) => e.toJson())
      .toList(),
};

DetailedFieldType _$DetailedFieldTypeFromJson(Map<String, dynamic> json) =>
    DetailedFieldType(
      $enumDecode(_$FieldTypeEnumMap, json['fieldType']),
      $enumDecode(_$AlphabetTypeEnumMap, json['alphabetType']),
    );

Map<String, dynamic> _$DetailedFieldTypeToJson(DetailedFieldType instance) =>
    <String, dynamic>{
      'fieldType': _$FieldTypeEnumMap[instance.fieldType]!,
      'alphabetType': _$AlphabetTypeEnumMap[instance.alphabetType]!,
    };

const _$AlphabetTypeEnumMap = {
  AlphabetType.latin: 'latin',
  AlphabetType.arabic: 'arabic',
  AlphabetType.cyrillic: 'cyrillic',
  AlphabetType.greek: 'greek',
};

DocumentFilter _$DocumentFilterFromJson(Map<String, dynamic> json) =>
    DocumentFilter(
      country: $enumDecodeNullable(_$CountryIDEnumMap, json['country']),
      region: $enumDecodeNullable(_$RegionIDEnumMap, json['region']),
      documentType: $enumDecodeNullable(
        _$DocumentTypeIDEnumMap,
        json['documentType'],
      ),
    );

Map<String, dynamic> _$DocumentFilterToJson(DocumentFilter instance) =>
    <String, dynamic>{
      'country': _$CountryIDEnumMap[instance.country],
      'region': _$RegionIDEnumMap[instance.region],
      'documentType': _$DocumentTypeIDEnumMap[instance.documentType],
    };

const _$CountryIDEnumMap = {
  CountryID.none: 'none',
  CountryID.albania: 'albania',
  CountryID.algeria: 'algeria',
  CountryID.argentina: 'argentina',
  CountryID.australia: 'australia',
  CountryID.austria: 'austria',
  CountryID.azerbaijan: 'azerbaijan',
  CountryID.bahrain: 'bahrain',
  CountryID.bangladesh: 'bangladesh',
  CountryID.belgium: 'belgium',
  CountryID.bosniaAndHerzegovina: 'bosniaAndHerzegovina',
  CountryID.brunei: 'brunei',
  CountryID.bulgaria: 'bulgaria',
  CountryID.bambodia: 'bambodia',
  CountryID.canada: 'canada',
  CountryID.chile: 'chile',
  CountryID.colombia: 'colombia',
  CountryID.costaRica: 'costaRica',
  CountryID.croatia: 'croatia',
  CountryID.cyprus: 'cyprus',
  CountryID.czechia: 'czechia',
  CountryID.denmark: 'denmark',
  CountryID.dominicanRepublic: 'dominicanRepublic',
  CountryID.egypt: 'egypt',
  CountryID.estonia: 'estonia',
  CountryID.finland: 'finland',
  CountryID.france: 'france',
  CountryID.georgia: 'georgia',
  CountryID.germany: 'germany',
  CountryID.ghana: 'ghana',
  CountryID.greece: 'greece',
  CountryID.guatemala: 'guatemala',
  CountryID.hongKong: 'hongKong',
  CountryID.hungary: 'hungary',
  CountryID.india: 'india',
  CountryID.indonesia: 'indonesia',
  CountryID.ireland: 'ireland',
  CountryID.israel: 'israel',
  CountryID.italy: 'italy',
  CountryID.jordan: 'jordan',
  CountryID.kazakhstan: 'kazakhstan',
  CountryID.kenya: 'kenya',
  CountryID.kosovo: 'kosovo',
  CountryID.kuwait: 'kuwait',
  CountryID.latvia: 'latvia',
  CountryID.lithuania: 'lithuania',
  CountryID.malaysia: 'malaysia',
  CountryID.maldives: 'maldives',
  CountryID.malta: 'malta',
  CountryID.mauritius: 'mauritius',
  CountryID.mexico: 'mexico',
  CountryID.morocco: 'morocco',
  CountryID.netherlands: 'netherlands',
  CountryID.newZealand: 'newZealand',
  CountryID.nigeria: 'nigeria',
  CountryID.pakistan: 'pakistan',
  CountryID.panama: 'panama',
  CountryID.paraguay: 'paraguay',
  CountryID.philippines: 'philippines',
  CountryID.poland: 'poland',
  CountryID.portugal: 'portugal',
  CountryID.puertoRico: 'puertoRico',
  CountryID.qatar: 'qatar',
  CountryID.romania: 'romania',
  CountryID.russia: 'russia',
  CountryID.saudiArabia: 'saudiArabia',
  CountryID.serbia: 'serbia',
  CountryID.singapore: 'singapore',
  CountryID.slovakia: 'slovakia',
  CountryID.slovenia: 'slovenia',
  CountryID.southAfrica: 'southAfrica',
  CountryID.spain: 'spain',
  CountryID.sweden: 'sweden',
  CountryID.switzerland: 'switzerland',
  CountryID.taiwan: 'taiwan',
  CountryID.thailand: 'thailand',
  CountryID.tunisia: 'tunisia',
  CountryID.turkey: 'turkey',
  CountryID.uae: 'uae',
  CountryID.gganda: 'gganda',
  CountryID.uK: 'uK',
  CountryID.ukraine: 'ukraine',
  CountryID.usa: 'usa',
  CountryID.vietnam: 'vietnam',
  CountryID.brazil: 'brazil',
  CountryID.norway: 'norway',
  CountryID.oman: 'oman',
  CountryID.ecuador: 'ecuador',
  CountryID.elSalvador: 'elSalvador',
  CountryID.sriLanka: 'sriLanka',
  CountryID.peru: 'peru',
  CountryID.uruguay: 'uruguay',
  CountryID.bahamas: 'bahamas',
  CountryID.bermuda: 'bermuda',
  CountryID.bolivia: 'bolivia',
  CountryID.china: 'china',
  CountryID.europeanUnion: 'europeanUnion',
  CountryID.haiti: 'haiti',
  CountryID.honduras: 'honduras',
  CountryID.iceland: 'iceland',
  CountryID.japan: 'japan',
  CountryID.luxembourg: 'luxembourg',
  CountryID.montenegro: 'montenegro',
  CountryID.nicaragua: 'nicaragua',
  CountryID.southKorea: 'southKorea',
  CountryID.venezuela: 'venezuela',
  CountryID.afghanistan: 'afghanistan',
  CountryID.alandIslands: 'alandIslands',
  CountryID.americanSamoa: 'americanSamoa',
  CountryID.andorra: 'andorra',
  CountryID.angola: 'angola',
  CountryID.anguilla: 'anguilla',
  CountryID.antarctica: 'antarctica',
  CountryID.antiguaAndBarbuda: 'antiguaAndBarbuda',
  CountryID.armenia: 'armenia',
  CountryID.aruba: 'aruba',
  CountryID.bailiwickOfGuernsey: 'bailiwickOfGuernsey',
  CountryID.bailiwickOfJersey: 'bailiwickOfJersey',
  CountryID.barbados: 'barbados',
  CountryID.belarus: 'belarus',
  CountryID.belize: 'belize',
  CountryID.benin: 'benin',
  CountryID.bhutan: 'bhutan',
  CountryID.bonaireSaintEustatiusAndSaba: 'bonaireSaintEustatiusAndSaba',
  CountryID.botswana: 'botswana',
  CountryID.bouvetIsland: 'bouvetIsland',
  CountryID.britishIndianOceanTerritory: 'britishIndianOceanTerritory',
  CountryID.burkinaFaso: 'burkinaFaso',
  CountryID.burundi: 'burundi',
  CountryID.cameroon: 'cameroon',
  CountryID.capeVerde: 'capeVerde',
  CountryID.caribbeanNetherlands: 'caribbeanNetherlands',
  CountryID.caymanIslands: 'caymanIslands',
  CountryID.centralAfricanRepublic: 'centralAfricanRepublic',
  CountryID.chad: 'chad',
  CountryID.christmasIsland: 'christmasIsland',
  CountryID.cocosIslands: 'cocosIslands',
  CountryID.comoros: 'comoros',
  CountryID.congo: 'congo',
  CountryID.cookIslands: 'cookIslands',
  CountryID.cuba: 'cuba',
  CountryID.curacao: 'curacao',
  CountryID.democraticRepublicOfTheCongo: 'democraticRepublicOfTheCongo',
  CountryID.djibouti: 'djibouti',
  CountryID.dominica: 'dominica',
  CountryID.eastTimor: 'eastTimor',
  CountryID.equatorialGuinea: 'equatorialGuinea',
  CountryID.eritrea: 'eritrea',
  CountryID.ethiopia: 'ethiopia',
  CountryID.falklandIslands: 'falklandIslands',
  CountryID.faroeIslands: 'faroeIslands',
  CountryID.federatedStatesOfMicronesia: 'federatedStatesOfMicronesia',
  CountryID.fiji: 'fiji',
  CountryID.frenchGuiana: 'frenchGuiana',
  CountryID.frenchPolynesia: 'frenchPolynesia',
  CountryID.frenchSouthernTerritories: 'frenchSouthernTerritories',
  CountryID.gabon: 'gabon',
  CountryID.gambia: 'gambia',
  CountryID.gibraltar: 'gibraltar',
  CountryID.greenland: 'greenland',
  CountryID.grenada: 'grenada',
  CountryID.guadeloupe: 'guadeloupe',
  CountryID.guam: 'guam',
  CountryID.guinea: 'guinea',
  CountryID.guineaBissau: 'guineaBissau',
  CountryID.guyana: 'guyana',
  CountryID.heardIslandAndMcdonaldIslands: 'heardIslandAndMcdonaldIslands',
  CountryID.iran: 'iran',
  CountryID.iraq: 'iraq',
  CountryID.isleOfMan: 'isleOfMan',
  CountryID.ivoryCoast: 'ivoryCoast',
  CountryID.jamaica: 'jamaica',
  CountryID.kiribati: 'kiribati',
  CountryID.kyrgyzstan: 'kyrgyzstan',
  CountryID.laos: 'laos',
  CountryID.lebanon: 'lebanon',
  CountryID.lesotho: 'lesotho',
  CountryID.liberia: 'liberia',
  CountryID.libya: 'libya',
  CountryID.liechtenstein: 'liechtenstein',
  CountryID.macau: 'macau',
  CountryID.madagascar: 'madagascar',
  CountryID.malawi: 'malawi',
  CountryID.mali: 'mali',
  CountryID.marshallIslands: 'marshallIslands',
  CountryID.martinique: 'martinique',
  CountryID.mauritania: 'mauritania',
  CountryID.mayotte: 'mayotte',
  CountryID.moldova: 'moldova',
  CountryID.monaco: 'monaco',
  CountryID.mongolia: 'mongolia',
  CountryID.montserrat: 'montserrat',
  CountryID.mozambique: 'mozambique',
  CountryID.myanmar: 'myanmar',
  CountryID.namibia: 'namibia',
  CountryID.nauru: 'nauru',
  CountryID.nepal: 'nepal',
  CountryID.newCaledonia: 'newCaledonia',
  CountryID.niger: 'niger',
  CountryID.niue: 'niue',
  CountryID.norfolkIsland: 'norfolkIsland',
  CountryID.northernCyprus: 'northernCyprus',
  CountryID.northernMarianaIslands: 'northernMarianaIslands',
  CountryID.northKorea: 'northKorea',
  CountryID.northMacedonia: 'northMacedonia',
  CountryID.palau: 'palau',
  CountryID.palestine: 'palestine',
  CountryID.papuaNewGuinea: 'papuaNewGuinea',
  CountryID.pitcairn: 'pitcairn',
  CountryID.reunion: 'reunion',
  CountryID.rwanda: 'rwanda',
  CountryID.saintBarthelemy: 'saintBarthelemy',
  CountryID.saintHelenaAscensionAndTristianDaCunha:
      'saintHelenaAscensionAndTristianDaCunha',
  CountryID.saintKittsAndNevis: 'saintKittsAndNevis',
  CountryID.saintLucia: 'saintLucia',
  CountryID.saintMartin: 'saintMartin',
  CountryID.saintPierreAndMiquelon: 'saintPierreAndMiquelon',
  CountryID.saintVincentAndTheGrenadines: 'saintVincentAndTheGrenadines',
  CountryID.samoa: 'samoa',
  CountryID.sanMarino: 'sanMarino',
  CountryID.saoTomeAndPrincipe: 'saoTomeAndPrincipe',
  CountryID.senegal: 'senegal',
  CountryID.seychelles: 'seychelles',
  CountryID.sierraLeone: 'sierraLeone',
  CountryID.sintMaarten: 'sintMaarten',
  CountryID.solomonIslands: 'solomonIslands',
  CountryID.somalia: 'somalia',
  CountryID.southGeorgiaAndTheSouthSandwichIslands:
      'southGeorgiaAndTheSouthSandwichIslands',
  CountryID.southSudan: 'southSudan',
  CountryID.sudan: 'sudan',
  CountryID.suriname: 'suriname',
  CountryID.svalbardAndJanMayen: 'svalbardAndJanMayen',
  CountryID.eswatini: 'eswatini',
  CountryID.syria: 'syria',
  CountryID.tajikistan: 'tajikistan',
  CountryID.tanzania: 'tanzania',
  CountryID.togo: 'togo',
  CountryID.tokelau: 'tokelau',
  CountryID.tonga: 'tonga',
  CountryID.trinidadAndTobago: 'trinidadAndTobago',
  CountryID.turkmenistan: 'turkmenistan',
  CountryID.turksAndCaicosIslands: 'turksAndCaicosIslands',
  CountryID.tuvalu: 'tuvalu',
  CountryID.unitedStatesMinorOutlyingIslands:
      'unitedStatesMinorOutlyingIslands',
  CountryID.uzbekistan: 'uzbekistan',
  CountryID.vanuatu: 'vanuatu',
  CountryID.vaticanCity: 'vaticanCity',
  CountryID.virginIslandsBritish: 'virginIslandsBritish',
  CountryID.virginIslandsOfTheUnitedStates: 'virginIslandsOfTheUnitedStates',
  CountryID.wallisAndFutuna: 'wallisAndFutuna',
  CountryID.westernSahara: 'westernSahara',
  CountryID.yemen: 'yemen',
  CountryID.yugoslavia: 'yugoslavia',
  CountryID.zambia: 'zambia',
  CountryID.zimbabwe: 'zimbabwe',
  CountryID.schengenArea: 'schengenArea',
  CountryID.saintThomasAndPrince: 'saintThomasAndPrince',
};

const _$RegionIDEnumMap = {
  RegionID.none: 'none',
  RegionID.alabama: 'alabama',
  RegionID.alaska: 'alaska',
  RegionID.alberta: 'alberta',
  RegionID.arizona: 'arizona',
  RegionID.arkansas: 'arkansas',
  RegionID.australianCapitalTerritory: 'australianCapitalTerritory',
  RegionID.britishColumbia: 'britishColumbia',
  RegionID.california: 'california',
  RegionID.colorado: 'colorado',
  RegionID.connecticut: 'connecticut',
  RegionID.delaware: 'delaware',
  RegionID.districtOfColumbia: 'districtOfColumbia',
  RegionID.florida: 'florida',
  RegionID.georgia: 'georgia',
  RegionID.hawaii: 'hawaii',
  RegionID.idaho: 'idaho',
  RegionID.illinois: 'illinois',
  RegionID.indiana: 'indiana',
  RegionID.iowa: 'iowa',
  RegionID.kansas: 'kansas',
  RegionID.kentucky: 'kentucky',
  RegionID.louisiana: 'louisiana',
  RegionID.maine: 'maine',
  RegionID.manitoba: 'manitoba',
  RegionID.maryland: 'maryland',
  RegionID.massachusetts: 'massachusetts',
  RegionID.michigan: 'michigan',
  RegionID.minnesota: 'minnesota',
  RegionID.mississippi: 'mississippi',
  RegionID.missouri: 'missouri',
  RegionID.montana: 'montana',
  RegionID.nebraska: 'nebraska',
  RegionID.nevada: 'nevada',
  RegionID.newBrunswick: 'newBrunswick',
  RegionID.newHampshire: 'newHampshire',
  RegionID.newJersey: 'newJersey',
  RegionID.newMexico: 'newMexico',
  RegionID.newSouthWales: 'newSouthWales',
  RegionID.newYork: 'newYork',
  RegionID.northernTerritory: 'northernTerritory',
  RegionID.northCarolina: 'northCarolina',
  RegionID.northDakota: 'northDakota',
  RegionID.novaScotia: 'novaScotia',
  RegionID.ohio: 'ohio',
  RegionID.oklahoma: 'oklahoma',
  RegionID.ontario: 'ontario',
  RegionID.oregon: 'oregon',
  RegionID.pennsylvania: 'pennsylvania',
  RegionID.quebec: 'quebec',
  RegionID.queensland: 'queensland',
  RegionID.rhodeIsland: 'rhodeIsland',
  RegionID.saskatchewan: 'saskatchewan',
  RegionID.southAustralia: 'southAustralia',
  RegionID.southCarolina: 'southCarolina',
  RegionID.southDakota: 'southDakota',
  RegionID.tasmania: 'tasmania',
  RegionID.tennessee: 'tennessee',
  RegionID.texas: 'texas',
  RegionID.utah: 'utah',
  RegionID.vermont: 'vermont',
  RegionID.victoria: 'victoria',
  RegionID.virginia: 'virginia',
  RegionID.washington: 'washington',
  RegionID.westernAustralia: 'westernAustralia',
  RegionID.westVirginia: 'westVirginia',
  RegionID.wisconsin: 'wisconsin',
  RegionID.wyoming: 'wyoming',
  RegionID.yukon: 'yukon',
  RegionID.ciudadDeMexico: 'ciudadDeMexico',
  RegionID.jalisco: 'jalisco',
  RegionID.newfoundlandAndLabrador: 'newfoundlandAndLabrador',
  RegionID.nuevoLeon: 'nuevoLeon',
  RegionID.bajaCalifornia: 'bajaCalifornia',
  RegionID.chihuahua: 'chihuahua',
  RegionID.guanajuato: 'guanajuato',
  RegionID.guerrero: 'guerrero',
  RegionID.mexico: 'mexico',
  RegionID.michoacan: 'michoacan',
  RegionID.newYorkCity: 'newYorkCity',
  RegionID.tamaulipas: 'tamaulipas',
  RegionID.veracruz: 'veracruz',
  RegionID.chiapas: 'chiapas',
  RegionID.coahuila: 'coahuila',
  RegionID.durango: 'durango',
  RegionID.guerreroCocula: 'guerreroCocula',
  RegionID.guerreroJuchitan: 'guerreroJuchitan',
  RegionID.guerreroTepecoacuilco: 'guerreroTepecoacuilco',
  RegionID.guerreroTlacoapa: 'guerreroTlacoapa',
  RegionID.gujarat: 'gujarat',
  RegionID.hidalgo: 'hidalgo',
  RegionID.karnataka: 'karnataka',
  RegionID.kerala: 'kerala',
  RegionID.khyberPakhtunkhwa: 'khyberPakhtunkhwa',
  RegionID.madhyaPradesh: 'madhyaPradesh',
  RegionID.maharashtra: 'maharashtra',
  RegionID.morelos: 'morelos',
  RegionID.nayarit: 'nayarit',
  RegionID.oaxaca: 'oaxaca',
  RegionID.puebla: 'puebla',
  RegionID.punjab: 'punjab',
  RegionID.queretaro: 'queretaro',
  RegionID.sanLuisPotosi: 'sanLuisPotosi',
  RegionID.sinaloa: 'sinaloa',
  RegionID.sonora: 'sonora',
  RegionID.tabasco: 'tabasco',
  RegionID.tamilNadu: 'tamilNadu',
  RegionID.yucatan: 'yucatan',
  RegionID.zacatecas: 'zacatecas',
  RegionID.aguascalientes: 'aguascalientes',
  RegionID.bajaCaliforniaSur: 'bajaCaliforniaSur',
  RegionID.campeche: 'campeche',
  RegionID.colima: 'colima',
  RegionID.quintanaRooBenitoJuarez: 'quintanaRooBenitoJuarez',
  RegionID.quintanaRoo: 'quintanaRoo',
  RegionID.quintanaRooSolidaridad: 'quintanaRooSolidaridad',
  RegionID.tlaxcala: 'tlaxcala',
  RegionID.quintanaRooCozumel: 'quintanaRooCozumel',
  RegionID.saoPaolo: 'saoPaolo',
  RegionID.rioDeJaneiro: 'rioDeJaneiro',
  RegionID.rioGrandeDoSul: 'rioGrandeDoSul',
  RegionID.northWestTerritories: 'northWestTerritories',
  RegionID.nunavut: 'nunavut',
  RegionID.princeEdwardIsland: 'princeEdwardIsland',
  RegionID.distritoFederal: 'distritoFederal',
  RegionID.maranhao: 'maranhao',
  RegionID.matoGrosso: 'matoGrosso',
  RegionID.minasGerais: 'minasGerais',
  RegionID.para: 'para',
  RegionID.parana: 'parana',
  RegionID.pernambuco: 'pernambuco',
  RegionID.santaCatarina: 'santaCatarina',
  RegionID.andhraPradesh: 'andhraPradesh',
  RegionID.ceara: 'ceara',
  RegionID.goias: 'goias',
  RegionID.guerreroAcapulcoDeJuarez: 'guerreroAcapulcoDeJuarez',
  RegionID.haryana: 'haryana',
  RegionID.sergipe: 'sergipe',
  RegionID.alagos: 'alagos',
  RegionID.bangsamoro: 'bangsamoro',
  RegionID.telangana: 'telangana',
  RegionID.acre: 'acre',
  RegionID.espiritoSanto: 'espiritoSanto',
  RegionID.matoGrossoDoSul: 'matoGrossoDoSul',
  RegionID.paraiba: 'paraiba',
  RegionID.piaui: 'piaui',
  RegionID.rioGrandeDoNorte: 'rioGrandeDoNorte',
  RegionID.tocantins: 'tocantins',
  RegionID.odisha: 'odisha',
  RegionID.uttarakhand: 'uttarakhand',
};

const _$DocumentTypeIDEnumMap = {
  DocumentTypeID.none: 'none',
  DocumentTypeID.consularId: 'consularId',
  DocumentTypeID.dl: 'dl',
  DocumentTypeID.dlPublicServicesCard: 'dlPublicServicesCard',
  DocumentTypeID.employmentPass: 'employmentPass',
  DocumentTypeID.finCard: 'finCard',
  DocumentTypeID.id: 'id',
  DocumentTypeID.multipurposeId: 'multipurposeId',
  DocumentTypeID.myKad: 'myKad',
  DocumentTypeID.myKid: 'myKid',
  DocumentTypeID.myPR: 'myPR',
  DocumentTypeID.myTentera: 'myTentera',
  DocumentTypeID.panCard: 'panCard',
  DocumentTypeID.professionalId: 'professionalId',
  DocumentTypeID.publicServicesCard: 'publicServicesCard',
  DocumentTypeID.residencePermit: 'residencePermit',
  DocumentTypeID.residentId: 'residentId',
  DocumentTypeID.temporaryResidencePermit: 'temporaryResidencePermit',
  DocumentTypeID.voterId: 'voterId',
  DocumentTypeID.workPermit: 'workPermit',
  DocumentTypeID.iKad: 'iKad',
  DocumentTypeID.militaryId: 'militaryId',
  DocumentTypeID.myKas: 'myKas',
  DocumentTypeID.docialSecurityCard: 'docialSecurityCard',
  DocumentTypeID.healthInsuranceCard: 'healthInsuranceCard',
  DocumentTypeID.passport: 'passport',
  DocumentTypeID.sPass: 'sPass',
  DocumentTypeID.addressCard: 'addressCard',
  DocumentTypeID.alienId: 'alienId',
  DocumentTypeID.alienPassport: 'alienPassport',
  DocumentTypeID.greenCard: 'greenCard',
  DocumentTypeID.minorsId: 'minorsId',
  DocumentTypeID.postalId: 'postalId',
  DocumentTypeID.professionalDl: 'professionalDl',
  DocumentTypeID.taxId: 'taxId',
  DocumentTypeID.weaponPermit: 'weaponPermit',
  DocumentTypeID.visa: 'visa',
  DocumentTypeID.borderCrossingCard: 'borderCrossingCard',
  DocumentTypeID.driverCard: 'driverCard',
  DocumentTypeID.globalEntryCard: 'globalEntryCard',
  DocumentTypeID.mypolis: 'mypolis',
  DocumentTypeID.nexusCard: 'nexusCard',
  DocumentTypeID.passportCard: 'passportCard',
  DocumentTypeID.proofOfAgeCard: 'proofOfAgeCard',
  DocumentTypeID.refugeeId: 'refugeeId',
  DocumentTypeID.tribalId: 'tribalId',
  DocumentTypeID.veteranId: 'veteranId',
  DocumentTypeID.citizenshipCertificate: 'citizenshipCertificate',
  DocumentTypeID.myNumberCard: 'myNumberCard',
  DocumentTypeID.consularPassport: 'consularPassport',
  DocumentTypeID.minorsPassport: 'minorsPassport',
  DocumentTypeID.minorsPublicServicesCard: 'minorsPublicServicesCard',
  DocumentTypeID.drivingPriviligeCard: 'drivingPriviligeCard',
  DocumentTypeID.asylumRequest: 'asylumRequest',
  DocumentTypeID.driverQualificationCard: 'driverQualificationCard',
  DocumentTypeID.provisionalDl: 'provisionalDl',
  DocumentTypeID.refugeePassport: 'refugeePassport',
  DocumentTypeID.specialId: 'specialId',
  DocumentTypeID.uniformedServicesId: 'uniformedServicesId',
  DocumentTypeID.immigrantVisa: 'immigrantVisa',
  DocumentTypeID.consularVoterId: 'consularVoterId',
  DocumentTypeID.twicCard: 'twicCard',
  DocumentTypeID.exitEntryPermit: 'exitEntryPermit',
  DocumentTypeID.mainlandTravelPermitTaiwan: 'mainlandTravelPermitTaiwan',
  DocumentTypeID.nbiClearance: 'nbiClearance',
  DocumentTypeID.proofOfRegistration: 'proofOfRegistration',
  DocumentTypeID.temporaryProtectionPermit: 'temporaryProtectionPermit',
  DocumentTypeID.afghanCitizenCard: 'afghanCitizenCard',
  DocumentTypeID.eId: 'eId',
  DocumentTypeID.pass: 'pass',
  DocumentTypeID.sisId: 'sisId',
  DocumentTypeID.asicCard: 'asicCard',
  DocumentTypeID.bidoonCard: 'bidoonCard',
  DocumentTypeID.interimHealthInsuranceCard: 'interimHealthInsuranceCard',
  DocumentTypeID.nonVoterId: 'nonVoterId',
  DocumentTypeID.reciprocalHealthInsuranceCard: 'reciprocalHealthInsuranceCard',
  DocumentTypeID.vehicleRegistration: 'vehicleRegistration',
  DocumentTypeID.esaadCard: 'esaadCard',
  DocumentTypeID.registrationCertificate: 'registrationCertificate',
  DocumentTypeID.medicalMarijuanaId: 'medicalMarijuanaId',
  DocumentTypeID.nonCardTribalId: 'nonCardTribalId',
  DocumentTypeID.diplomaticId: 'diplomaticId',
  DocumentTypeID.emergencyPassport: 'emergencyPassport',
  DocumentTypeID.temporaryPassport: 'temporaryPassport',
  DocumentTypeID.metisFederationCard: 'metisFederationCard',
  DocumentTypeID.socialSecurityCard: 'socialSecurityCard',
  DocumentTypeID.adrCertificate: 'adrCertificate',
  DocumentTypeID.ninCard: 'ninCard',
  DocumentTypeID.mysssCard: 'mysssCard',
  DocumentTypeID.gendarmerieId: 'gendarmerieId',
  DocumentTypeID.policeId: 'policeId',
  DocumentTypeID.originCard: 'originCard',
};

DocumentNumberRedactionSettings _$DocumentNumberRedactionSettingsFromJson(
  Map<String, dynamic> json,
) => DocumentNumberRedactionSettings(
  prefixDigitsVisible: (json['prefixDigitsVisible'] as num?)?.toInt(),
  suffixDigitsVisible: (json['suffixDigitsVisible'] as num?)?.toInt(),
);

Map<String, dynamic> _$DocumentNumberRedactionSettingsToJson(
  DocumentNumberRedactionSettings instance,
) => <String, dynamic>{
  'prefixDigitsVisible': instance.prefixDigitsVisible,
  'suffixDigitsVisible': instance.suffixDigitsVisible,
};
